<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 11:11:57 --> Severity: Notice --> Undefined variable: objPHPExcel C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 273
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 11:50:33 --> Severity: Notice --> Undefined variable: objPHPExcel C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 199
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 11:51:22 --> Severity: Warning --> date() expects at least 1 parameter, 0 given C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 207
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> Undefined variable: i C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 258
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> String offset cast occurred C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 258
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> Undefined variable: i C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 259
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> String offset cast occurred C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 259
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> Undefined variable: i C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 260
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> String offset cast occurred C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 260
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> Undefined variable: i C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 261
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Notice --> String offset cast occurred C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 261
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\VisionCenter\system\core\Exceptions.php:271) C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 312
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\VisionCenter\system\core\Exceptions.php:271) C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 313
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 15:23:38 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\VisionCenter\system\core\Exceptions.php:271) C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 314
ERROR - 2019-05-30 15:42:24 --> 404 Page Not Found: Production/Delivery/C_Delivery/Packets_Pending
ERROR - 2019-05-30 15:42:24 --> 404 Page Not Found: Production/Delivery/C_Delivery/style.css
ERROR - 2019-05-30 15:43:27 --> 404 Page Not Found: Production/Delivery/C_Delivery/Enlist_Packets_Pending
ERROR - 2019-05-30 15:43:27 --> 404 Page Not Found: Production/Delivery/C_Delivery/style.css
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: index C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 1
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: index C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 1
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 8
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: index C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 1
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: index C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 1
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 8
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:19 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 8
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Tabs_Modulated_Pending.php 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 8
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:43:57 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 44
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: data_order C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 63
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-30 16:44:29 --> Severity: Notice --> Undefined variable: packs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Modulated_Pending.php 80
ERROR - 2019-05-30 16:47:29 --> 404 Page Not Found: Dist/js
