<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-04-25 08:14:45 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Se produjo un error durante el intento de conexi�n ya que la parte conectada no respondi� adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexi�n establecida ya que el host conectado no ha podido responder.
 C:\xampp\htdocs\VisionCenter\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2019-04-25 08:14:45 --> Unable to connect to the database
ERROR - 2019-04-25 08:14:47 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Se produjo un error durante el intento de conexi�n ya que la parte conectada no respondi� adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexi�n establecida ya que el host conectado no ha podido responder.
 C:\xampp\htdocs\VisionCenter\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2019-04-25 08:14:47 --> Unable to connect to the database
ERROR - 2019-04-25 08:15:00 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Se produjo un error durante el intento de conexi�n ya que la parte conectada no respondi� adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexi�n establecida ya que el host conectado no ha podido responder.
 C:\xampp\htdocs\VisionCenter\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2019-04-25 08:15:00 --> Unable to connect to the database
ERROR - 2019-04-25 08:18:36 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 08:19:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 08:42:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 09:12:36 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 10:06:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 10:07:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 10:33:07 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 11:47:34 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 11:48:03 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 11:48:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 12:22:46 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:22:48 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 26
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:22:52 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 26
ERROR - 2019-04-25 12:24:05 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 37
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 37
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:08 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:24:25 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
ERROR - 2019-04-25 12:27:40 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_total_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_packets C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$quantity_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:27:41 --> Severity: Notice --> Undefined property: stdClass::$number_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
ERROR - 2019-04-25 12:35:55 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 37
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 37
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:35:56 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 38
ERROR - 2019-04-25 12:38:16 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:38:17 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
ERROR - 2019-04-25 12:40:07 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:40:07 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 26
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:40:12 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 26
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:40:12 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 26
ERROR - 2019-04-25 12:40:33 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 12:42:00 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:02 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
ERROR - 2019-04-25 12:42:56 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:42:57 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:43:49 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
ERROR - 2019-04-25 12:45:19 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:19 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
ERROR - 2019-04-25 12:45:34 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:45:35 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
ERROR - 2019-04-25 12:46:44 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 32
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 33
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 34
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 35
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 12:46:45 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
ERROR - 2019-04-25 12:54:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 13:05:51 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 14:28:27 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 14:49:20 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 14:49:57 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 14:50:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 14:52:07 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 14:52:08 --> Severity: Notice --> Undefined index: res C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 62
ERROR - 2019-04-25 14:52:28 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 14:52:29 --> Severity: Notice --> Undefined variable: record C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 14:52:29 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 14:52:38 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:02:38 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 15:02:39 --> Severity: Notice --> Undefined variable: record C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 15:02:39 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 15:02:39 --> Severity: Notice --> Undefined variable: table_pack C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 54
ERROR - 2019-04-25 15:03:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:04:27 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:05:48 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:08:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:09:38 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 15:09:51 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 16:27:52 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:27:53 --> Severity: Notice --> Undefined index: res C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 62
ERROR - 2019-04-25 16:28:23 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 16:29:15 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:29:16 --> Severity: Notice --> Undefined variable: record C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:29:16 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 16:29:47 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:29:48 --> Severity: Notice --> Undefined variable: record C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:29:48 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 16:29:56 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:29:57 --> Severity: Notice --> Undefined index: record C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 63
ERROR - 2019-04-25 16:30:09 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 16:30:39 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:30:40 --> Severity: Notice --> Undefined variable: rs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:30:40 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 16:32:12 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:32:13 --> Severity: Notice --> Undefined variable: rs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:32:13 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 16:32:58 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:32:59 --> Severity: Notice --> Undefined variable: rs C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 16:32:59 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 20
ERROR - 2019-04-25 16:33:12 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 16:36:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 16:36:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 17:03:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 17:03:56 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 17:05:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-25 17:05:18 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 17:05:25 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 17:06:22 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
ERROR - 2019-04-25 17:07:32 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 17:07:34 --> Query error: Unknown column 'P.weight_per_supplies' in 'field list' - Invalid query: SELECT P.id_supplies,P.name,P.code,P.weight_per_supplies,S.quantity, S.`order`, S.id_order_supplies, S.exclude  FROM pro_supplies P INNER JOIN access_order_supplies S ON S.id_supplies = P.id_supplies WHERE S.`order` = 20216  ORDER BY S.id_order_supplies ASC
ERROR - 2019-04-25 17:08:23 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-25 17:08:25 --> Query error: Table 'vision.access_order_package_supplies_detail' doesn't exist - Invalid query: SELECT aos.id_order_supplies,SUM(aos.quantity_packaged) AS quantity_packaged FROM access_order_package_supplies ao  INNER JOIN access_order_package_supplies_detail aos ON ao.id_order_package_supplies = aos.access_order_package_supplies  WHERE aos.id_order_supplies = 560 GROUP BY aos.id_order_supplies
ERROR - 2019-04-25 17:09:43 --> 404 Page Not Found: Dist/js
