<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:01 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:08:02 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 202
ERROR - 2019-04-23 07:13:18 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:14:53 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:14:53 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:14:53 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:14:53 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:15:27 --> Severity: Notice --> Undefined property: C_Delivery::$package_number C:\xampp\htdocs\VisionCenter\system\core\Model.php 73
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:15:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 - Invalid query: SELECT A.* FROM access_order_package_supplies_detail A INNER JOIN access_order_package_supplies O ON A.access_order_package_supplies = O.id_order_package_supplies WHERE A.id_order_supplies = 617 AND O.`order` = 20216 AND O.number_pack = 
ERROR - 2019-04-23 07:22:10 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:22:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:22:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:22:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:22:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:24:15 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:24:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:24:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:24:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:24:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:41:19 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 07:41:28 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:38 --> Severity: Notice --> Undefined property: C_Delivery::$package_number C:\xampp\htdocs\VisionCenter\system\core\Model.php 73
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:41:38 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM access_order_package_supplies WHERE number_pack =  AND `order` = 20216
ERROR - 2019-04-23 07:42:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 07:43:00 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:43:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:43:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:43:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:43:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:45:11 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:48:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:48:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:48:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:48:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:49:26 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:49:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:49:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:49:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:49:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:50:28 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 07:50:33 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:50:34 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:50:34 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:50:34 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:50:34 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 07:58:02 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:04 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:04 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:04 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:04 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:05 --> Severity: Warning --> Missing argument 2 for M_Delivery::get_supplies_detail(), called in C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php on line 77 and defined C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 89
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:05 --> Severity: Notice --> Undefined variable: number_pack C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 92
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 07:58:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON as.id_order_package_supplies = a.access_order_package_supplies WHERE id_order' at line 1 - Invalid query: SELECT a.* FROM access_order_package_supplies_detail a INNER JOIN access_order_package_supplies as  ON as.id_order_package_supplies = a.access_order_package_supplies WHERE id_order_supplies = 617  AND as.number_pack = 
ERROR - 2019-04-23 08:00:26 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:00:31 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:00:31 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:00:31 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:00:31 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:00:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON as.id_order_package_supplies = a.access_order_package_supplies WHERE id_order' at line 1 - Invalid query: SELECT a.* FROM access_order_package_supplies_detail a INNER JOIN access_order_package_supplies as  ON as.id_order_package_supplies = a.access_order_package_supplies WHERE id_order_supplies = 617  AND as.number_pack = 1
ERROR - 2019-04-23 08:02:16 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 08:02:19 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:02:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:02:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:02:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 08:02:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:10:01 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:10:02 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:10:02 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:10:02 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:10:02 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:18:04 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:05 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:05 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:05 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:05 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:18:53 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:53 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:53 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:53 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:18:53 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:23:10 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:23:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:23:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:23:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:23:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:54:59 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 09:55:08 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:09 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:09 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:09 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:09 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 09:55:33 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:34 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:34 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:34 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 09:55:34 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 10:23:59 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 10:24:02 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:24:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:24:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:24:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:24:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 10:33:03 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-23 10:33:10 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:33:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:33:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:33:11 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:33:11 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 10:39:00 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:39:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:39:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:39:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 10:39:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 11:27:48 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:27:48 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:27:48 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:27:48 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:27:48 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 11:28:26 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:28:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:28:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:28:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:28:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 11:29:23 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:29:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:29:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:29:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:29:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 11:31:15 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:31:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:31:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:31:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:31:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 11:58:14 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:58:15 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:58:15 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:58:15 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 11:58:15 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:10:53 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:10:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:10:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:10:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:10:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:11:23 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:11:26 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:11:26 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:11:26 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:11:26 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:18:32 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:18:33 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:18:33 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:18:33 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:18:33 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:28:58 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:28:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:28:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:28:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:28:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:29:14 --> Severity: Notice --> Undefined property: C_Delivery::$M_delivery C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 140
ERROR - 2019-04-23 12:29:51 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:29:52 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:29:52 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:29:52 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:29:52 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:30:05 --> Severity: Notice --> Undefined property: C_Delivery::$M_delivery C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 140
ERROR - 2019-04-23 12:31:25 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:31:26 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:31:26 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:31:26 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:31:26 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:33:16 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:33:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:33:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:33:16 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:33:16 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:35:23 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:35:55 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:35:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:47:58 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:47:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:47:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:47:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:47:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:49:28 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:49:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:49:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:49:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:49:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:51:40 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:51:41 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:51:41 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:51:41 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:51:41 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:53:16 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:53:17 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:53:17 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:53:17 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:53:17 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 12:54:00 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:54:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:54:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:54:01 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 12:54:01 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 13:05:13 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 13:05:14 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 14:32:02 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:32:05 --> Severity: Notice --> Undefined property: stdClass::$quantity_packaged C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 80
ERROR - 2019-04-23 14:44:46 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:44:47 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 14:59:48 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 14:59:49 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 15:14:54 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:14:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:15:13 --> Severity: Warning --> Missing argument 4 for M_Delivery::get_supplies_detail2(), called in C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php on line 124 and defined C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 104
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:15:13 --> Severity: Notice --> Undefined variable: order C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 107
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:15:13 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND a.access_order_package_supplies = 617  ORDER BY a.id_order_supplies ASC' at line 1 - Invalid query: SELECT a.* FROM access_order_package_supplies_detail a INNER JOIN access_order_package_supplies aos  ON aos.id_order_package_supplies = a.access_order_package_supplies WHERE a.id_order_supplies = 1  AND aos.number_pack = 20216 AND aos.`order` =  AND a.access_order_package_supplies = 617  ORDER BY a.id_order_supplies ASC
ERROR - 2019-04-23 15:16:25 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:16:25 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-23 15:17:19 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-23 15:17:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
