<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-03-20 07:59:37 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 07:59:43 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 08:19:12 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 08:30:45 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 08:35:07 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:16 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:21 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:26 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:31 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:41 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:51 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:35:56 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:01 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:06 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:11 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:36:15 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:21 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:26 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:31 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:41 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:51 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:36:56 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:36:58 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:04 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:09 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:14 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:19 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:29 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:34 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:44 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:49 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:54 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:37:59 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:04 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:38:09 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:22 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:32 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:42 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:47 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:52 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:38:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:02 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:22 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:39:31 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:39:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:39:59 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:08 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:14 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:18 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:23 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:29 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:34 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:38 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:44 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:49 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:40:54 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:41:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:03 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:08 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:13 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:19 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:24 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:29 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:34 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:43 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:48 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:54 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:42:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:04 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:09 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:14 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:18 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` =  AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:43:20 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:31 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:41 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:43:51 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:43:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:02 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:22 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:32 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:42 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:47 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:52 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:44:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:02 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:22 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-20 08:45:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd =' at line 1 - Invalid query: SELECT dd.*, d.weight_estimate_trunk FROM dis_request_sd_detail dd INNER JOIN dis_request_sd dWHERE dd.id_request_sd = d.id_request_sd AND dd.`order` = 20298 AND dd.id_request_sd = 4
ERROR - 2019-03-20 08:58:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:04:00 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:07:04 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:11:49 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:14:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:14:29 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:30:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:30:43 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:43:37 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:53:46 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:53:52 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:53:56 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:53:58 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:54:05 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:54:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:54:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:54:36 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:54:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:55:34 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:55:39 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:56:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:56:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:56:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:56:49 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:56:59 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:57:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:57:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:57:16 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 09:57:19 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 10:00:29 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 10:00:32 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:41:21 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:41:34 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:41:55 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:43:27 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:43:49 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:43:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:44:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:44:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:45:33 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:45:57 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:46:04 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:46:28 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:46:32 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:46:40 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 12:46:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:14:28 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:14:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:14:55 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:15:13 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:16:47 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:16:57 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:24:00 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:24:12 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:24:39 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:24:43 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:25:20 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:25:26 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:33:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:33:58 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:34:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:34:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:36:23 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:36:48 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:36:52 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:36:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:37:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:37:47 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:37:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:38:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:39:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:11 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:26 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:50 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:40:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:43:28 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 14:43:32 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:01:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:01:56 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:06:58 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:07:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:07:45 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:10:27 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:10:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:12:01 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:12:17 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:33:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:33:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:38:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:39:38 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-20 15:43:38 --> 404 Page Not Found: Dist/js
