<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:02:19 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Edit_Manual.php 15
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:08:46 --> Severity: Notice --> Undefined variable: rs C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 128
ERROR - 2019-04-24 08:28:49 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:28:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 08:29:18 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 08:29:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 09:51:58 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:51:59 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:27 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:28 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Undefined variable: value C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:52:29 --> Severity: Notice --> Trying to get property of non-object C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
ERROR - 2019-04-24 09:54:40 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:54:41 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:05 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:06 --> Severity: Notice --> Undefined variable: quantity_packaged_sum C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 168
ERROR - 2019-04-24 09:55:49 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:55:50 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 09:58:42 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 09:58:43 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 10:08:56 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:08:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 10:17:55 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 10:17:56 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:01:22 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:01:24 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:30:27 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:30:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:34:31 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:34:32 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:34:59 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:00 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:35:18 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:35:32 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:35:33 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:49:26 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:49:27 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:50:18 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:50:19 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:51:16 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:51:17 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:54:54 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:54:55 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 11:56:19 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 11:56:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 15:16:38 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:16:39 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 15:20:03 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:20:05 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 15:21:01 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:02 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 15:21:19 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 15:21:20 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:32:10 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:32:10 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:35:26 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:35:28 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:50:01 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:50:03 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:54:29 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:54:30 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:55:22 --> 404 Page Not Found: Dist/js
ERROR - 2019-04-24 16:55:36 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:55:38 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:56:05 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:06 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:56:36 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:56:36 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:57:04 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:57:04 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
ERROR - 2019-04-24 16:59:28 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$code C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 30
User ---> Ivan Contreras ID (15) - ERROR - 2019-04-24 16:59:29 --> Severity: Notice --> Undefined property: stdClass::$name C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 31
