<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:29:35 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:30:24 --> Severity: Notice --> Undefined variable: total C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:45:20 --> Severity: Notice --> Undefined variable: id_order_supplies C:\xampp\htdocs\VisionCenter\application\controllers\Production\Delivery\C_Delivery.php 112
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:45:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 - Invalid query: SELECT AO.* FROM access_order_package_supplies A INNER JOIN access_order_package_supplies_detail AO  ON A.id_order_package_supplies = AO.access_order_package_supplies WHERE A.`order` = 20216  AND AO.id_order_supplies = 
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:45:47 --> Severity: Notice --> Undefined variable: packed C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\pdf\V_Content_Detail_Pack_Supplies_Pending.php 2
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 08:59:20 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:05:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:11:31 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:11:41 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:11:59 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:12:21 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:14:49 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:15:59 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:16:12 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:21:23 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: weight C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Pack.php 36
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 27
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 28
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: delivered C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 31
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:21:40 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:23:00 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:23:18 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:23:18 --> Severity: Warning --> Division by zero C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 74
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:23:18 --> Severity: Notice --> Undefined variable: total_quantity C:\xampp\htdocs\VisionCenter\application\views\Production\Delivery\Supplies\Enlist\V_Table_Supplies.php 78
ERROR - 2019-05-23 09:24:13 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:25:14 --> Severity: Notice --> Undefined variable: array_id_update C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 437
ERROR - 2019-05-23 09:25:43 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:27:39 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 348
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:27:39 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 348
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:27:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:28:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:28:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:28:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
ERROR - 2019-05-23 09:33:48 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:35:31 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 09:35:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
ERROR - 2019-05-23 09:36:04 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:38:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:39:56 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:44:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:44:50 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:45:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:45:55 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:50:13 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:56:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:57:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:58:13 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:59:01 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 09:59:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:00:47 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:03:12 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:03:12 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:03:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
ERROR - 2019-05-23 10:03:19 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:03:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:04:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:05:07 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:05:23 --> Severity: Notice --> Undefined variable: id_order_package_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:05:23 --> Severity: Notice --> Undefined variable: id_supplies C:\xampp\htdocs\VisionCenter\application\models\Production\Delivery\M_Delivery.php 349
User ---> Ivan Contreras ID (15) - ERROR - 2019-05-23 10:05:23 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND id_supplies =  AND `order` = 20216' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE id_order_package_supplies =   AND id_supplies =  AND `order` = 20216
ERROR - 2019-05-23 10:07:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:07:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:10:28 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:11:31 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:11:50 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:13:48 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:15:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:20:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:20:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:24:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:28:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:35:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:36:40 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:37:56 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:38:04 --> 404 Page Not Found: Production/Delivery/C_Delivery/Enlist_Supplies_Pendings
ERROR - 2019-05-23 10:38:04 --> 404 Page Not Found: Production/Delivery/C_Delivery/style.css
ERROR - 2019-05-23 10:38:25 --> 404 Page Not Found: Production/Delivery/C_Delivery/Enlist_Supplies_Pendings
ERROR - 2019-05-23 10:38:25 --> 404 Page Not Found: Production/Delivery/C_Delivery/style.css
ERROR - 2019-05-23 10:38:46 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:38:51 --> 404 Page Not Found: Production/Delivery/C_Delivery/Enlist_Supplies_Pendings
ERROR - 2019-05-23 10:38:51 --> 404 Page Not Found: Production/Delivery/C_Delivery/style.css
ERROR - 2019-05-23 10:39:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:55:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 10:55:48 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 12:50:27 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:23:51 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:24:02 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:24:15 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:24:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:24:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:25:22 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:26:00 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:26:29 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 14:44:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 15:07:03 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 15:09:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 15:10:45 --> 404 Page Not Found: Dist/js
ERROR - 2019-05-23 15:11:03 --> 404 Page Not Found: Dist/js
