<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-03-08 07:33:10 --> 404 Page Not Found: Images/icons
ERROR - 2019-03-08 07:33:50 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 07:56:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 07:57:10 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 08:47:39 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 09:01:45 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 09:40:24 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:40:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:41:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 09:41:52 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
ERROR - 2019-03-08 09:42:43 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:42:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:43:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order =  GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 ORDER BY id_request_sd' at line 1 - Invalid query: SELECT * FROM dis_request_sd_subdetail_package WHERE order = 20237 ORDER BY id_request_sd
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE order = 20237 GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 09:44:33 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:53 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:44:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:03 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:08 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:13 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 09:45:15 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:23 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:28 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:33 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:38 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:43 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:48 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:53 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:45:58 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 09:45:59 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:07 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:17 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:22 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:27 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:32 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:37 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:42 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 09:46:43 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:51 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:46:56 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:01 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:06 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:11 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:16 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:21 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:26 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:31 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:41 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:46 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:51 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:47:56 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:01 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:06 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:11 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:16 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:21 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:26 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 09:48:31 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 10:01:16 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:45 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:50 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:01:55 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:00 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:05 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:15 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:20 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:25 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:30 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:35 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 10:02:40 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY id_status ORDER BY id_request_sd ASC' at line 1 - Invalid query: SELECT id_status, COUNT(*) AS total FROM dis_request_sd_subdetail_package WHERE dis_request_sd_subdetail_package.`order` =  GROUP BY id_status ORDER BY id_request_sd ASC
ERROR - 2019-03-08 10:02:44 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 10:10:22 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 10:10:55 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 10:11:07 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 10:44:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 10:45:17 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 11:13:17 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 11:13:43 --> 404 Page Not Found: Dist/js
User ---> Ivan Contreras ID (15) - ERROR - 2019-03-08 12:03:36 --> Severity: Notice --> Undefined variable: datos C:\xampp\htdocs\VisionCenter\application\views\Monitoreo\principal.php 28
ERROR - 2019-03-08 12:03:37 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:03:51 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:11:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:12:58 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:17:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:39:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:40:43 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:42:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 12:42:50 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:27:25 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:27:38 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:36:06 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:38:17 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:52:01 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:52:11 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:52:33 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:52:43 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:53:24 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 14:53:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:13:57 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:18:14 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:18:37 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:20:21 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:20:59 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:25:11 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:31:52 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:38:42 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:40:52 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 15:47:59 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:23:53 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:23:54 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:24:34 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:24:47 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/_lib/buttons
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/C_Monitoreo/app_menu_pri_pag_ini.php
ERROR - 2019-03-08 16:30:46 --> 404 Page Not Found: Monitoreo/C_Monitoreo/style.css
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/C_Monitoreo/app_menu_pri_pag_ini.php
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/_lib/buttons
ERROR - 2019-03-08 16:33:33 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:33:34 --> 404 Page Not Found: Monitoreo/C_Monitoreo/style.css
ERROR - 2019-03-08 16:34:18 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:34:35 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:34:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/_lib/buttons
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/C_Monitoreo/app_menu_pri_pag_ini.php
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/_lib/css
ERROR - 2019-03-08 16:34:42 --> 404 Page Not Found: Monitoreo/C_Monitoreo/style.css
ERROR - 2019-03-08 16:36:39 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:40:41 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:42:32 --> 404 Page Not Found: Dist/js
ERROR - 2019-03-08 16:42:38 --> 404 Page Not Found: Dist/js
